# Basic Configuration
baseURL = "/"
languageCode = "en-us"
title = ""
theme = "hugo-saasify-theme"

# Required Features
pygmentsCodeFences = true  # Enable syntax highlighting
pygmentsUseClasses = true
enableEmoji = true        # Enable emoji support
enableGitInfo = true      # Enable Git info for lastmod

# Required Module Configuration
[module]
  [module.hugoVersion]
    extended = true
    min = "0.80.0"

# Required Build Configuration
[build]
  writeStats = true      # Required for TailwindCSS

# Required Markup Configuration
[markup]
  [markup.highlight]
    noClasses = false
    lineNos = true
    codeFences = true
  [markup.goldmark.renderer]
    unsafe = true       # Allow HTML in markdown
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

# Theme Parameters
[params]
  description = "Red Hat Service Catalog"
  author = "Your Name"
  #logo = "/images/rh-logo.png"      # Path to your logo
  logo = "/catalog/images/rh-svc-logo.png"
  # Google Analytics ID (e.g., "G-XXXXXXXXXX")
  # googleAnalytics = "G-XXXXXXXXXX"  # Only enabled in production

  # Header Configuration
  [params.header]
    background = "bg-white/80 backdrop-blur-sm"
    border = "border-b border-gray-100"
    
    # Header Logo
    [params.header.logo]
      src = "/catalog/images/rh-svc-logo2.png"
    
    # Header Buttons (optional)
    [params.header.buttons]
      [params.header.buttons.getStarted]
        text = "서비스 신청하기"
        url = "/get-started"
#      [params.header.buttons.signIn]
#        text = "서비스 문의"
#        url = "/signin"


  # Global CTA Configuration (optional)
  [params.cta]
    enable = true
    title = "Ready to Get Started?"
    description = "Join companies using our platform"
    [params.cta.primary_button]
      text = "Get Started Free"
      url = "/get-started"
    [params.cta.secondary_button]
      text = "Book Demo"
      url = "/demo"

  # Social Media Links (optional)
  [params.social]
    linkedin = "https://linkedin.com/in/yourusername"
    twitter = "https://twitter.com/yourusername"
    github = "https://github.com/yourusername"

# Navigation Menu
[menu]
  [[menu.main]]
    name = "AI"
    weight = 1
    [menu.main.params]
      has_submenu = true
      submenu = [
        { name = "AI 네비게이트", url = "/catalog/features/ai-1/" },
        { name = "AI 인큐베이터", url = "/catalog/features/ai-2/" },
        { name = "AIOps 파운데이션", url = "/catalog/features/ai-3/" },
        { name = "MLOps 파운데이션", url = "/catalog/features/ai-4/" }
      ]
  [[menu.main]]
    name = "쿠버네티스 가상화"
    weight = 2
    [menu.main.params]
      has_submenu = true
      submenu = [
        { name = "가상화 전환 평가 서비스", url = "/catalog/features/virtual-1/" },
        { name = "가상화 전환 서비스", url = "/catalog/features/virtual-2/" }
      ]
  [[menu.main]]
    name = "자동화"
    weight = 3
    [menu.main.params]
      has_submenu = true
      submenu = [
        { name = "자동화 네비게이트", url = "/catalog/features/automation-1/" },
        { name = "자동화 플랫폼 구축", url = "/catalog/features/automation-2/" }
      ]
  #[[menu.main]]
  #  name = "가상화 구축 서비스"
  #  url = "/pricing"
  #  weight = 2
  #[[menu.main]]
  #  name = "Blog"
  #  url = "/blog"
  #  weight = 3
